version: "2"
services:
  install-deps:
    image: node:6.3.0
    volumes:
      - ../../:/working_dir
    working_dir: /working_dir
    entrypoint: npm install
    environment:
      - NPM_CONFIG_REGISTRY
